AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: simple-lambdas-zip

Resources:

  SimpleLambdaZip:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      MemorySize: 512
      Handler: com.efxcode.aws.HelloWorld::handler
      CodeUri: target/lambda.zip
