AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Simple Lambdas

Resources:
  SimpleLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SimpleLambda
      Runtime: java8
      MemorySize: 512
      Handler: com.efxcode.aws.ContextAndEnvLambda::handleContextRequest  #the method to invoke
      CodeUri: target/lambda.jar
      Environment:
        Variables:
          REQ_AUTH_NAME: cq#28gb